import Head from 'next/head'
import { trpc } from '@/sdk/lib/trpc'

import { Inter } from '@next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const { data } = trpc.vtex.product.useQuery({
    productId: '115498942',
  })

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className}>
        <h1 className="text-6xl font-bold">Teste</h1>
      </main>
    </>
  )
}
