import './globals.css'
import { Jost } from 'next/font/google'
import { Analytics } from '@vercel/analytics/react'

const jost = Jost({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={jost.className}>
        {children}
        <Analytics />
      </body>
    </html>
  )
}
